"""IP-XACT / SystemRDL 导出器。

M4 实现简化版：
- IP-XACT：register/bitfield → SPIRIT/IP-XACT XML 1685-2014 子集
- SystemRDL：register/bitfield → SystemRDL 2.0 子集

目的是与下游 EDA / 寄存器生成工具对接，让 spec 抽取的成果可直接喂给芯片设计流程。
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from xml.sax.saxutils import escape

from docgraph.graph.schema import EdgeKind, Node, NodeKind
from docgraph.graph.sqlite_store import SQLiteGraphStore
from docgraph.graph.store import NodeQuery


@dataclass
class ExportResult:
    format: str
    output_path: Path
    registers: int
    bitfields: int


# ---------------------------------------------------------------------------
# IP-XACT
# ---------------------------------------------------------------------------


def export_ipxact(
    store: SQLiteGraphStore,
    out_path: Path,
    *,
    family: str = "unknown",
    component: str = "spec",
    register_name: str | None = None,
) -> ExportResult:
    """导出 IP-XACT 1685-2014 minimal subset."""
    nodes = _select_registers(store, register_name)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<ipxact:component xmlns:ipxact="http://www.accellera.org/XMLSchema/IPXACT/1685-2014">',
        f'  <ipxact:vendor>docgraph</ipxact:vendor>',
        f'  <ipxact:library>{escape(family)}</ipxact:library>',
        f'  <ipxact:name>{escape(component)}</ipxact:name>',
        '  <ipxact:version>0.1</ipxact:version>',
        '  <ipxact:memoryMaps>',
        '    <ipxact:memoryMap>',
        f'      <ipxact:name>{escape(component)}_regs</ipxact:name>',
        '      <ipxact:addressBlock>',
        f'        <ipxact:name>{escape(component)}_block</ipxact:name>',
        '        <ipxact:baseAddress>0x0</ipxact:baseAddress>',
        '        <ipxact:range>0x1000</ipxact:range>',
        '        <ipxact:width>32</ipxact:width>',
    ]

    total_bf = 0
    for reg in nodes:
        attrs = reg.attrs or {}
        addr = attrs.get("address") or attrs.get("offset") or "0x0"
        width = attrs.get("width") or 32
        access = attrs.get("access") or ""
        reset = attrs.get("reset_value") or ""
        lines.append("        <ipxact:register>")
        lines.append(f"          <ipxact:name>{escape(reg.name)}</ipxact:name>")
        lines.append(f"          <ipxact:description>{escape(reg.summary or '')}</ipxact:description>")
        lines.append(f"          <ipxact:addressOffset>{escape(str(addr))}</ipxact:addressOffset>")
        lines.append(f"          <ipxact:size>{int(width)}</ipxact:size>")
        if access:
            lines.append(f"          <ipxact:access>{escape(_map_access_ipxact(access))}</ipxact:access>")

        bfs = _bitfields_of(store, reg)
        for bf in bfs:
            ba = bf.attrs or {}
            hi, lo = int(ba.get("bit_high", 0)), int(ba.get("bit_low", 0))
            lines.append("          <ipxact:field>")
            lines.append(f"            <ipxact:name>{escape(bf.name)}</ipxact:name>")
            lines.append(f"            <ipxact:description>{escape(ba.get('description') or '')}</ipxact:description>")
            lines.append(f"            <ipxact:bitOffset>{lo}</ipxact:bitOffset>")
            lines.append(f"            <ipxact:bitWidth>{hi - lo + 1}</ipxact:bitWidth>")
            if ba.get("access"):
                lines.append(f"            <ipxact:access>{escape(_map_access_ipxact(ba['access']))}</ipxact:access>")
            if ba.get("reset"):
                lines.append("            <ipxact:resets><ipxact:reset>"
                             f"<ipxact:value>{escape(str(ba['reset']))}</ipxact:value>"
                             "</ipxact:reset></ipxact:resets>")
            lines.append("          </ipxact:field>")
            total_bf += 1
        lines.append("        </ipxact:register>")

    lines += [
        '      </ipxact:addressBlock>',
        '    </ipxact:memoryMap>',
        '  </ipxact:memoryMaps>',
        '</ipxact:component>',
    ]
    out_path.write_text("\n".join(lines), encoding="utf-8")
    return ExportResult(format="ipxact", output_path=out_path, registers=len(nodes), bitfields=total_bf)


# ---------------------------------------------------------------------------
# SystemRDL
# ---------------------------------------------------------------------------


def export_systemrdl(
    store: SQLiteGraphStore,
    out_path: Path,
    *,
    family: str = "unknown",
    component: str = "spec",
    register_name: str | None = None,
) -> ExportResult:
    """导出 SystemRDL 2.0 minimal subset."""
    nodes = _select_registers(store, register_name)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    lines: list[str] = [
        f"// Generated by docgraph — family={family}, component={component}",
        f"addrmap {_id(component)}_top {{",
        f'  desc = "Auto-generated from docgraph for {family}";',
    ]
    total_bf = 0
    for reg in nodes:
        attrs = reg.attrs or {}
        width = int(attrs.get("width") or 32)
        addr = attrs.get("address") or attrs.get("offset") or None
        lines.append("")
        lines.append(f"  reg {{")
        lines.append(f'    name = "{_esc(reg.name)}";')
        if reg.summary:
            lines.append(f'    desc = "{_esc(reg.summary)}";')
        lines.append(f"    regwidth = {width};")
        bfs = _bitfields_of(store, reg)
        for bf in bfs:
            ba = bf.attrs or {}
            hi, lo = int(ba.get("bit_high", 0)), int(ba.get("bit_low", 0))
            lines.append(f"    field {{")
            if ba.get("description"):
                lines.append(f'      desc = "{_esc(ba["description"])}";')
            if ba.get("access"):
                lines.append(f"      sw = {_map_access_rdl(ba['access'])}; hw = rw;")
            if ba.get("reset") is not None and ba.get("reset") != "":
                lines.append(f"      reset = {_format_reset(ba['reset'])};")
            lines.append(f"    }} {_id(bf.name)}[{hi}:{lo}];")
            total_bf += 1
        suffix = f" @ {addr}" if addr else ""
        lines.append(f"  }} {_id(reg.name)}{suffix};")
    lines.append("};")
    out_path.write_text("\n".join(lines), encoding="utf-8")
    return ExportResult(format="systemrdl", output_path=out_path, registers=len(nodes), bitfields=total_bf)


# ---------------------------------------------------------------------------
# 共用
# ---------------------------------------------------------------------------


def _select_registers(store: SQLiteGraphStore, name: str | None) -> list[Node]:
    if name:
        return store.search_nodes(NodeQuery(name=name, kind=NodeKind.REGISTER, limit=1))
    return store.search_nodes(NodeQuery(kind=NodeKind.REGISTER, limit=10000))


def _bitfields_of(store: SQLiteGraphStore, reg: Node) -> list[Node]:
    sub = store.neighbors(reg.id, edge_kinds=[EdgeKind.HAS_BITFIELD], depth=1)
    bfs = [n for n in sub.nodes if n.kind == NodeKind.BITFIELD]
    bfs.sort(key=lambda n: -int(n.attrs.get("bit_high", 0)))
    return bfs


def _map_access_ipxact(s: str) -> str:
    s = (s or "").upper()
    return {
        "RW": "read-write", "RO": "read-only", "WO": "write-only",
        "W1C": "read-write", "RZ": "read-only",
    }.get(s, "read-write")


def _map_access_rdl(s: str) -> str:
    s = (s or "").upper()
    return {"RW": "rw", "RO": "r", "WO": "w", "W1C": "rw", "RZ": "r"}.get(s, "rw")


def _id(name: str) -> str:
    import re
    return re.sub(r"\W", "_", name)


def _esc(s: str) -> str:
    return (s or "").replace('"', '\\"').replace("\n", " ")[:200]


def _format_reset(v: object) -> str:
    s = str(v).strip()
    if s.lower().startswith("0x"):
        return s
    if s.startswith("0b"):
        try:
            return f"{int(s, 2):#x}"
        except ValueError:
            return "0"
    try:
        return f"{int(s):#x}"
    except ValueError:
        return "0"
